version: '3'

services:
  records-ms:
    image: records-ms-image
    build:
        context: ./
        dockerfile: Dockerfile
    ports:
      - 8090:8080
    depends_on:
      - mongo-db
    links:
      - mongo-db:mongoserver

  mongo-db:
    image: mongo
    ports: 
      - 27017:27017
    volumes:
      - data:/data/db
    expose: 
      - 27017

volumes:
  data:
